# Generated by Django 4.2.23 on 2025-07-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('current_ip', models.GenericIPAddressField()),
                ('status', models.CharField(default='Offline', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('settings_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='camera_manager.camera')),
            ],
        ),
    ]
