# Generated by Django 4.2.23 on 2025-07-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='current_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
